### ISSUE TITLE
Rotation direction WARN

### ISSUE THREAD

**Issue by SlimeDog** [eldoriarpg/BigDoorOpener#11]
Spigot 1.16.1
BigDoors Alpha 0.1.8.20
BigDoorsOpener 1.2a-BETA

On server startup
[QUOTE][16:55:54] [Server thread/INFO]: [BigDoorsOpener] Locale messages_de_DE.properties is up to date.
[16:55:54] [Server thread/INFO]: [BigDoorsOpener] Locale messages_en_US.properties is up to date.
[16:55:54] [Server thread/INFO]: [BigDoorsOpener] Metrics enabled. Thank you very much!
[16:55:56] [Server thread/WARN]: [BigDoors] Rotation direction is null for door Dragonstone-portal-door-S (8)!
[16:55:56] [Server thread/WARN]: [BigDoors] Rotation direction is null for door Dragonstone-portal-door-N (9)![/QUOTE]
Four other doors, similarly configured in the same world, produce no warnings. The WARN messages occur only with BigDoorsOpener installed.

BigDoorsOpener/config.yml (relevant bits):
```
- ==: de.eldoria.bigdoorsopener.config.TimedDoor
  doorUID: '8'
  world: world_westeros
  position:
    ==: Vector
    x: 2510.0
    y: 76.5
    z: 2848.0
  permission: ''
  ticksClose: 13000
  ticksOpen: 1000
  range: 0.0
  invertOpen: false
- ==: de.eldoria.bigdoorsopener.config.TimedDoor
  doorUID: '9'
  world: world_westeros
  position:
    ==: Vector
    x: 2510.0
    y: 76.5
    z: 2851.5
  permission: ''
  ticksClose: 13000
  ticksOpen: 1000
  range: 0.0
  invertOpen: false
```
